/* auto-generated by stencil */
export namespace Components {
  interface OrcButton { variant?: "primary" | "secondary" | "danger"; size?: "sm" | "md" | "lg"; disabled?: boolean; loading?: boolean; }
  interface OrcBadge { variant?: "success" | "warning" | "danger" | "info" | "neutral"; dot?: boolean; }
  interface OrcStatCard { label: string; value: string; color?: string; subtitle?: string; }
  interface OrcModal { open: boolean; heading: string; }
  interface OrcProgressBar { value: number; max?: number; label?: string; }
  interface OrcSpinner { size?: "sm" | "md" | "lg"; }
  interface OrcToast { variant?: "success" | "error" | "info"; duration?: number; open?: boolean; }
  interface OrcDataTable { columns: string; sortable?: boolean; }
}

declare global {
  interface HTMLOrcButtonElement extends Components.OrcButton, HTMLElement {}
  interface HTMLOrcBadgeElement extends Components.OrcBadge, HTMLElement {}
  interface HTMLOrcStatCardElement extends Components.OrcStatCard, HTMLElement {}
  interface HTMLOrcModalElement extends Components.OrcModal, HTMLElement {}
  interface HTMLOrcProgressBarElement extends Components.OrcProgressBar, HTMLElement {}
  interface HTMLOrcSpinnerElement extends Components.OrcSpinner, HTMLElement {}
  interface HTMLOrcToastElement extends Components.OrcToast, HTMLElement {}
  interface HTMLOrcDataTableElement extends Components.OrcDataTable, HTMLElement {}
}
