/**
 * Cross-language parity check for the segmentation-mask RLE codec.
 *
 * WHY THIS EXISTS
 * The browser encodes what the user paints (maskCodec.ts); Python decodes it
 * for COCO export (labeling/mask_codec.py). Two independent implementations of
 * the same format is exactly the setup where a subtle divergence — a shift that
 * wraps, row-major instead of column-major, a dropped zero-length leading run —
 * does not throw. It writes masks that decode to the wrong pixels, and the only
 * symptom is "the exported segmentations look slightly off", discovered long
 * after the data was created.
 *
 * The fixture in tests/fixtures/mask_rle_vectors.json is generated BY the
 * Python encoder (tests/test_mask_codec.py covers Python against itself). This
 * script asserts the TypeScript side produces byte-identical output for the
 * same masks and decodes Python's output back to the same pixels.
 *
 * Run:  node --experimental-strip-types scripts/check_mask_codec_parity.mjs
 *
 * No build step and no npm install: Node 22.6+ strips TypeScript types on the
 * fly, so this runs against the real source file rather than a compiled copy
 * that could drift from it.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const { encodeCounts, decodeCounts, maskToRle, rleToMask, rleArea } = await import(
  join(root, "frontend/Frontend/src/app/pages/annotate/maskCodec.ts")
);

const cases = JSON.parse(
  readFileSync(join(root, "tests/fixtures/mask_rle_vectors.json"), "utf8")
);

let failures = 0;
for (const c of cases) {
  const data = Uint8Array.from(c.mask); // row-major, the layout a canvas gives us

  // 1. The TS encoder must produce exactly what Python produced.
  const rle = maskToRle(data, c.h, c.w);
  const encodeMatches = rle.counts === c.encoded;

  // 2. The TS decoder must read Python's output back to the same run lengths.
  const decoded = decodeCounts(c.encoded);
  const decodeMatches =
    decoded.length === c.counts.length && decoded.every((v, i) => v === c.counts[i]);

  // 3. Python's encoding must rehydrate to the original pixels in TS.
  const back = rleToMask({ size: [c.h, c.w], counts: c.encoded });
  let roundTrips = back.length === data.length;
  if (roundTrips) {
    for (let i = 0; i < data.length; i++) {
      if ((data[i] ? 1 : 0) !== back[i]) { roundTrips = false; break; }
    }
  }

  // 4. Derived area must agree with a direct count.
  const expectedArea = c.mask.reduce((a, b) => a + (b ? 1 : 0), 0);
  const areaMatches = rleArea(rle) === expectedArea;

  const ok = encodeMatches && decodeMatches && roundTrips && areaMatches;
  if (!ok) failures++;
  const detail = ok
    ? ""
    : `  (encode=${encodeMatches} decode=${decodeMatches} roundtrip=${roundTrips} area=${areaMatches})`;
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${c.name}${detail}`);
}

if (failures > 0) {
  console.error(
    `\n${failures} vector(s) differ between maskCodec.ts and labeling/mask_codec.py.\n` +
      "These MUST stay byte-identical: the browser encodes masks and Python decodes\n" +
      "them for export, so any divergence silently corrupts stored annotations."
  );
  process.exit(1);
}
console.log(`\nmaskCodec.ts matches mask_codec.py on all ${cases.length} vectors.`);
